### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by AYBarrett** [BarrettTechnology/proficio_toolbox#2]
error after Cmake ../ as follows:

robot@robot-desktop:~/proficio_toolbox/build$ make
Scanning dependencies of target homecheck
[ 20%] Building CXX object programs/CMakeFiles/homecheck.dir/homecheck.cpp.o
In file included from /usr/local/include/barrett/products/product_manager.h:47:0,
                 from /home/robot/proficio_toolbox/programs/homecheck.cpp:19:
/usr/local/include/barrett/products/gimbals_hand_controller.h:78:55: error: field initializer is not constant
make[2]: *** [programs/CMakeFiles/homecheck.dir/homecheck.cpp.o] Error 1
make[1]: *** [programs/CMakeFiles/homecheck.dir/all] Error 2
make: *** [all] Error 2

**Comment by mhariharasudan** [comment]
@amyblank This is the error that was caused due to the inclusion of CGAL. Can you either modify gimbals_hand_controller.h in libbarrett to reflect the constant or fix the issue with CGAL?

**Comment by amyblank** [comment]
As best I can tell from reading about this error, it has something to do with compiler options. I don't want to mess with these because I don't know what CGAL needs. However, I can make the change in libbarrett from 
`COUNTS_PER_RAD = 4096.0 / (2*M_PI);`
to 
`COUNTS_PER_RAD = 4096.0*M_1_PI/2.0;`
to fix the problem (at least on my system). This is better than replacing with the calculated value (651.898646904) because a person reading the code can still see where the number comes from.

**Comment by mhariharasudan** [comment]
This is fixed in libbarrett Pull Request #23
